server:
  name: Bulker
  version: 1.0.0
  http-version: HTTP/1.0
  host: 127.0.0.1
  port: 8080
  backlog: 50
  threadpool:
    core: 50
    max: 50
    keep-alive: 30
  charset: utf-8
  welcome: index.html
  virtual-host:
  - serverName: www.bulker1.com
    host: 127.0.0.1:8080
    doc-root: ./webapp
  - serverName: www.bulker2.com
    host: 127.0.0.1:8080
    doc-root: ./webapp
  servlet:
  - servletName: TimeServlet
    contextMapping: /time
    method:
    - methodName: getTime
      contextMapping: /GetTime
    servletClass: org.chaostocosmos.bulker.http.servlet.TimeServletImpl
    servletFilters:
    - org.chaostocosmos.bulker.http.filter.HttpURLFilter
messages:
  http:
    '200': OK
    '201': Created
    '202': Accepted
    '203': No Content
    '205': Reset Content
    '206': Partial Content (RFC 7233)
    '300': Multiple Choices
    '301': Moved Permanently
    '307': Temporary Redirect (since HTTP/1.1)
    '308': Permanent Redirect (RFC 7538)
    '400': Bad Request
    '401': Unauthorized (RFC 7235)
    '402': Payment Required
    '403': Forbidden
    '404': Not Found
    '405': Method Not Allowed
    '406': Not Acceptable
    '407': Proxy Authentication Required (RFC 7235)
    '408': Request Timeout
    '409': Conflict
    '412': Precondition Failed (RFC 7232)
    '413': Payload Too Large (RFC 7231)
    '414': URI Too Long (RFC 7231)
    '415': Unsupported Media Type (RFC 7231)
    '417': Expectation Failed
    '418': I'm a teapot (RFC 2324, RFC 7168)
    '421': Misdirected Request (RFC 7540)
    '423': Locked (WebDAV; RFC 4918)
    '429': Too Many Requests (RFC 6585)
    '431': Request Header Fields Too Large (RFC 6585)
    '451': Unavailable For Legal Reasons (RFC 7725)
    '500': Internal Server Error
    '501': Not Implemented
    '502': Bad Gateway
    '503': Service Unavailable
    '504': Gateway Timeout
    '505': HTTP Version Not Supported
    '507': Insufficient Storage (WebDAV; RFC 4918)
    '508': Loop Detected (WebDAV; RFC 5842)
    '510': Not Extended (RFC 2774)
    '511': Network Authentication Required (RFC 6585)
  debug:
    debug001: ''
  info:
    info001: 'ServletDescriptor annotation not found in class: {}'
    info002: ''
    info003: ''
  warn:
    warn001: 'Forbidden resources requested: {}'
  error:
    error001: There isn't exist path in servlet-method configuration.
    error002: There isn't exist http request type in servlet-method configuration.
    error003: 'Not supported http request method type : {}'
    error004: 'URI path can not use multiple method. path: {}'
    error005: 'Error in servlet method validate progress. Class: {}  Method: {}'
    error006: 'Invalid request line: {}'
    error007: 'Invalid header parameter: {}'
    error008: 'Error occurred in response header progress: {}'
    error009: 'Invalid method requested: {}'
    error010: 'Error in request process '
    error011: 'Can''t find Class which specified in config in classpath: {}'
    error012: 'Can''t find default constructor on Servlet class: {}'
    error013: Security problem occurred. check access security
    error014: Virtual host's 'host' expresstion is wrong!!!
    error015: Some problem occurred in Servlet loading progress
    error016: 'Not supported method type: {}'
    error017: 'Not supported method type: {}'
static-resource:
  '403': 403.html
  '404': 404.html
  '405': 405.html
  '500': 500.html
  '501': 501.html
