############################## Leap Server Configuration ##############################

server:
    version: 1.0.0
    connection: 
      connection-timeout: 30000
      backlog: 50
    
    performance: 
      file-buffer-size: 1024
      threadpool:
        core: 1
        max: 1
        keep-alive: 30
        queue-size: 1
      redirect:
        http://awesome:8082 : 20
        http://www.leap1.org:8081 : 80

    security:
      ssl:
        encryption: 'TLS'
        keystore: './config/ssl/leap-keystore.jks'
        passphrase: '939393'

############################## Default Hosts ##############################

    default-host:
      server-name: leap
      protocol: HTTP/1.1
      charset: 'utf-8'
      host: localhost
      port: 8080
      doc-root: ./home
      welcome: 'welcome.html'
      logs: 'logs/leap.log'
      log-level: 'DEBUG'
      users:
        - username: localhost
          password: 9393
          grant: ADMIN
        - username: guest
          password: guest
          grant: GUEST
      ip-filter: 
        allowed : ['*']
        forbidden : []
      resource:
        in-memory-filters: ['*.html']
        access-filters: ['*']
        forbidden-filters: []
      dynamic-classpath: 'd:/0.Github/leap/home/webapp/services'
      dynamic-packages: [
        "org.chaostocosmos.leap.http.services"
      ]
      spring-jpa-packages: [
        "org.chaostocosmos.leap.http.services", 
        "org.chaostocosmos.leap.http.services.datasource",
        "org.chaostocosmos.leap.http.services.entiry",
        "org.chaostocosmos.leap.http.services.repository"
      ]
      error-filters: [
        javax.net.ssl.SSLHandshakeException,
        java.net.SocketException
      ]

############################## Virtual Hosts ##############################

    virtual-host:
    - server-name: leap1
      protocol: HTTP/1.1
      charset: 'utf-8'
      host: awesome
      port: 8082
      doc-root: ./home1    
      welcome: 'welcome.html'
      logs: 'logs/leap.log'
      log-level: 'DEBUG'
      users:
        - username: awesome
          password: 9393
          grant: ADMIN
        - username: guest1
          password: guest1
          grant: GUEST
      ip-filter: 
        allowed : ['*']
        forbidden : []
      resource:
        in-memory-filters: ['*']
        access-filters: ['*']
        forbidden-filters: []
      dynamic-classpath: ''
      dynamic-packages: ["*"]
      spring-jpa-pakages: []
      error-filters: [
        javax.net.ssl.SSLHandshakeException,
        java.net.SocketException
      ]

    - server-name: leap2
      protocol: HTTP/1.1
      charset: 'utf-8'
      host: www.leap1.org
      port: 8081
      doc-root: ./home2
      welcome: 'welcome.html'
      logs: 'logs/leap.log'
      log-level: 'DEBUG'
      users:
        - username: leap1
          password: 9393
          grant: ADMIN
        - username: guest2
          password: guest2
          grant: GUEST
      ip-filter: 
        allowed : ['*']
        forbidden : []
      resource:
        in-memory-filters: ['*']
        access-filters: ['*']
        forbidden-filters: []
      dynamic-classpath: ''
      dynamic-packages: ["*"]
      spring-jpa-pakages: []
      error-filters: [
        javax.net.ssl.SSLHandshakeException,
        java.net.SocketException
      ]
