############################## Leap Server Configuration ##############################
server:
    version: 1.0
    connection: 
      connection-timeout: 30000
      backlog: 50
    
    performance: 
      file-buffer-size: 1024
      threadpool:
        core: 50
        max: 50
        keep-alive: 30

    security:
      ssl:
        encryption: 'TLS'
        keystore: './config/ssl/leap-keystore.jks'
        passphrase: '939393'

############################## Default Hosts ##############################

    default-host:
      server-name: leap
      protocol: HTTP/1.0
      charset: 'utf-8'
      host: localhost
      port: 8080
      users:
        - username: localhost
          password: 9393
          grant: ADMIN
        - username: guest
          password: guest
          grant: GUEST
      dynamic-classpaths: './home/webapp/services'
      resource:
        in-memory-filters: ['*.html']
        access-filters: ['*']
      error-filters: [
        javax.net.ssl.SSLHandshakeException,
        java.net.SocketException
      ]
      doc-root: ./home
      welcome: 'index.html'
      logs: 'logs/leap.log'
      log-level: 'DEBUG'

############################## Virtual Hosts ##############################

    virtual-host:
    - server-name: leap1
      protocol: HTTPS/1.0
      charset: 'utf-8'
      host: awesome
      port: 8082
      users:
        - username: awesome
          password: 9393
          grant: ADMIN
        - username: guest1
          password: guest1
          grant: GUEST
      dynamic-classpaths: ''
      resource:
        in-memory-filters: ['*.html']
        access-filters: ['*']
      error-filters: [
        javax.net.ssl.SSLHandshakeException,
        java.net.SocketException
      ]
      doc-root: ./home1    
      welcome: 'index.html'
      logs: 'logs/leap.log'
      log-level: 'DEBUG'

    - server-name: leap2
      protocol: HTTP/1.0
      charset: 'utf-8'
      host: www.leap1.org
      port: 8081
      users:
        - username: leap1
          password: 9393
          grant: ADMIN
        - username: guest2
          password: guest2
          grant: GUEST
      dynamic-classpaths: ''
      resource:
        in-memory-filters: ['*.html']
        access-filters: ['*']
      error-filters: [
        javax.net.ssl.SSLHandshakeException,
        java.net.SocketException
      ]
      doc-root: ./home2
      welcome: 'index.html'
      logs: 'logs/leap.log'
      log-level: 'DEBUG'
