############################## Hosts configuration ##############################
hosts:
############################## Default host configuration ##############################  
  - id: leap
    host: www.leap.com
    port: 9292
    connection-timeout: 5000
    backlog: 300
    request-blocking-interval: 10
    reponse-limit-bytes: 10240000
    protocol: HTTP
    protocol-version: 1.1
    timezone: Asia/Seoul 
    charset: utf-8
    index-page: welcome.html
    error-page: error.html
    context-filters: 
      access-filters: ['*']    
      forbidden-filters: []
    ip-filters: 
      allowed : ['*']
      forbidden : []
    session:
      apply: false
      length: 16
      encryption: SHA-256
      expire-days: 10      # day
      max-age-hours: 1     # hour
      timeout-seconds: 10  # second
    authentication: BASIC
    users:
      - username: admin
        password: '9393'
        role: ADMIN
      - username: guest
        password: '9393'
        role: GUEST
    security:
      encryption: 'TLS'
      keystore: './config/ssl/leap-keystore.jks'
      passphrase: '939393'
    logs: 
      path: logs/leap.log
      level: DEBUG
      details: true
    dynamic-classpath: []    

############################## Virtual host configuration ##############################
  - id: leap1
    host: www.leap-virtual.com
    port: 8889
    connection-timeout: 5000
    backlog: 300
    request-blocking-interval: 10
    reponse-limit-bytes: 10240000
    protocol: HTTP
    protocol-version: 1.1
    timezone: Asia/Seoul 
    charset: utf-8
    index-page: welcome.html
    error-page: error.html
    context-filters:
      access-filters: ['*']    
      forbidden-filters: []
    ip-filters: 
      allowed : ['*']
      forbidden : []
    session:
      apply: false
      length: 16
      encryption: SHA-256
      expire-days: 10      # day
      max-age-hours: 1     # hour
      timeout-seconds: 10  # second
    authentication: BASIC
    users:
      - username: admin
        password: 'admin'
        role: ADMIN
      - username: guest
        password: '9393'
        role: GUEST
    security:
      encryption: 'TLS'
      keystore: './config/ssl/leap-keystore.jks'
      passphrase: '939393'
    logs: 
      path: logs/leap.log
      level: DEBUG
      details: true
    dynamic-classpath: []    

 
