############################## Default Hosts ##############################
hosts:
  - id: leap
    default: true
    host: localhost
    port: 8080
    protocol: HTTP
    docroot: ./home
    welcome: welcome.html
    locale: Asia/Seoul    
    charset: utf-8
    authentication: NONE
    session:
      apply: false
      length: 16
      encryption: SHA-256
      expire-days: 10     # day
      max-age-hours: 1    # hour
      timeout-seconds: 60  # second
    ip-filters: 
      allowed : ['*']
      forbidden : []
    users:
      - username: localhost
        password: '9393'
        role: ADMIN
      - username: guest
        password: '9393'
        role: GUEST
    logs: 
      path: logs/leap.log
      level: DEBUG
      details: true
    error-details: true
    datasource: 
      driver-class: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://localhost:3306/leap
      user: root
      password: '9393'
    dynamic-classpath: ['']      
    resources:
      streaming-buffer-size: 102400
      in-memory-split-unit: 1024000
      in-memory-filters: ['*']
      access-filters: ['*']
      forbidden-filters: []    

############################## Virtual Hosts ##############################
