mime-type:
  text/plain:
  text/html:
  text/css :
  text/javascript:
  image/gif:
  image/png:
  image/jpeg:
  image/bmp:
  image/webp:
  audio/midi:
  audio/mpeg:
  audio/webm:
  audio/ogg:
  audio/wav:
  video/webm:
  video/ogg:
  application/octet-stream:
  application/pkcs12:
  application/vnd.mspowerpoint:
  application/xhtml+xml:
  application/xml:
  application/pdf:
  form-data:
  byteranges: