cpu: 
  id : cpu
  title: cpu
  codec: png
  save-path: monitor/cpu.png
  graph: line
  alpha: 0.6
  interpolate: linear
  width: '@width'
  height: '@height'
  x-index: 100
  y-index: '30,50,80,100'
  limit: 100
  unit: '%'
  elements: 
    - element: leap
      color: '180,130,130'
      values: []
    - element: system
      color: '180,180,140'
      values: []
memory: 
  id : memory
  title: memory
  codec: png
  save-path: monitor/memory.png
  graph: area
  alpha: 0.6
  interpolate: spline
  width: 800
  height: 500
  x-index: 100
  y-index: '@memoryUsedLeap, @memoryUsedPhysical'
  limit: '@memoryTotalPhysical'
  unit: mb
  elements: 
    - element: Physical Used
      color: '133,193,233'
      values: []
    - element: Physical Free
      color: '178,186,187'
      values: []
    - element: Leap Used
      color: '127,0,244'
      values: []
heap: 
  id : heap
  title: heap
  codec: png
  save-path: monitor/heap.png
  graph: area
  alpha: 0.6
  interpolate: spline
  width: '@width'
  height: '@height'
  x-index: 100
  y-index: '@heapMax, @heapInit, @heapCommited, @heapUsed'
  limit: '@heapMax * 1.3'
  unit: mb
  elements: 
    - element: Max
      color: '133,157,233'
      values: []
    - element: Committed
      color: '233,138,133'
      values: []
    - element: Init
      color: '200,133,233'
      values: []
    - element: Used
      color: '131,203,124'
      values: []
thread: 
  id : thread
  title: thread
  codec: png
  save-path: monitor/thread.png
  graph: line
  alpha: 0.6
  interpolate: spline
  width: '@width'
  height: '@height'
  x-index: 100
  y-index: '@threadCore, @threadMax'
  limit: '@threadMax * 3'
  unit: mb
  elements: 
    - element: Max
      color: '180,130,130'
      values: []
    - element: Core
      color: '150,200,158'
      values: []
    - element: Active
      color: '150,130,158'
      values: []
    - element: Queued
      color: '130,180,110'
      values: []

