############################## Default Hosts ##############################
hosts:
  - id: leap
    default: true
    host: localhost
    port: 8080
    protocol: HTTP
    protocol-version: 1.1
    docroot: ./home
    welcome: /templates/welcome.html
    locale: Asia/Seoul 
    charset: utf-8
    authentication: BASIC
    session:
      apply: false
      length: 16
      encryption: SHA-256
      expire-days: 10      # day
      max-age-hours: 1     # hour
      timeout-seconds: 10  # second
    ip-filters: 
      allowed : ['*']
      forbidden : []
    users:
      - username: localhost
        password: '9393'
        role: ADMIN
      - username: guest
        password: '9393'
        role: GUEST
    logs: 
      path: logs/leap.log
      level: DEBUG
      details: true
    error-details: true
    data-source: 
      - id: MYSQL
        driver-class: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3306/leap
        user: root
        password: '9393'
    dynamic-classpath: ['']      
    resources:
      streaming-buffer-size: 102400
      in-memory-split-unit: 1024000
      in-memory-filters: ['*']
      access-filters: ['*']
      forbidden-filters: []    

############################## Virtual Hosts ##############################

  - id: leap1
    default: false
    host: www.leap.org
    port: 8081
    protocol: HTTP
    protocol-version: 1.1
    docroot: ./home1
    welcome: /templates/welcome.html
    locale: Asia/Seoul 
    charset: utf-8
    authentication: BASIC
    session:
      apply: false
      length: 16
      encryption: SHA-256
      expire-days: 10      # day
      max-age-hours: 1     # hour
      timeout-seconds: 10  # second
    ip-filters: 
      allowed : ['*']
      forbidden : []
    users:
      - username: localhost
        password: '9393'
        role: ADMIN
      - username: guest
        password: '9393'
        role: GUEST
    logs: 
      path: logs/leap.log
      level: DEBUG
      details: true
    error-details: true
    data-source: 
      - id: MYSQL
        driver-class: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3306/leap
        user: root
        password: '9393'
    dynamic-classpath: ['']      
    resources:
      streaming-buffer-size: 102400
      in-memory-split-unit: 1024000
      in-memory-filters: ['*']
      access-filters: ['*']
      forbidden-filters: []    