mime-type:
  text:
    - text/plain
    - text/html
    - text/css 
    - text/javascript
  image:
    - image/gif
    - image/png
    - image/jpeg
    - image/bmp
    - image/webp
  audio:
    - audio/midi
    - audio/mpeg
    - audio/webm
    - audio/ogg
    - audio/wav
  video:
    - video/webm
    - video/ogg
  application:
    - application/octet-stream
    - application/pkcs12
    - application/vnd.mspowerpoint
    - application/xhtml+xml
    - application/xml
    - application/pdf
  multipart:
    - form-data
    - byteranges