server:
  version: 1.0.0
  http-version: HTTP/1.0
  server-name: leap
  host: localhost
  port: 8080
  users:
    - username: chaos930
      password: 9393
      grant: ADMIN      
    - username: guest
      password: guest
      grant: GUEST
  doc-root: ./home
  logs: 'logs/leap.log'
  log-level: 'DEBUG'
  charset: 'utf-8'
  welcome: 'index.html'
  backlog: 50
  upload-buffer-size: 10MB
  threadpool:
    core: 50
    max: 50
    keep-alive: 30
  virtual-host:
  - server-name: leap1
    host: 127.0.0.1
    port: 8080
    doc-root: ./home1
    welcome: 'index.html'
    logs: 'logs/leap.log'
    log-level: 'DEBUG'
  - server-name: leap2
    host: 192.168.1.28
    port: 8082
    doc-root: ./home2
    welcome: 'index.html'
    logs: 'logs/leap.log'
    log-level: 'DEBUG'
static-resource:
  'welcome': 'index.html'
  'response': 'response.html'