############################## Default Hosts ##############################
hosts:
  - id: leap
    default: true
    host: localhost
    port: 8080
    doc-root: ./home
    welcome: welcome.html
    locale: Asia/Seoul    
    charset: utf-8
    logs: 
      path: logs/leap.log
      level: DEBUG
      details: true
    datasource: 
      driver-class: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://localhost:3306/leap
      user: root
      password: '9393'
    authentication: BASIC
    security: 
      protocol: HTTP
      session:
        apply: true
        length: 16
        encryption: SHA-256
        expire-days: 10     # day
        max-age-hours: 1    # hour
        timeout-seconds: 5  # second
      ip-filters: 
        allowed : ['*']
        forbidden : []
      users:
        - username: localhost
          password: '9393'
          grant: ADMIN
        - username: guest
          password: '9393'
          grant: GUEST
    dynamic-classpath: ['']      
    resources:
      streaming-buffer-size: 409600
      in-memory-split-unit: 1024000
      in-memory-filters: ['*']
      access-filters: ['*']
      forbidden-filters: []    

############################## Virtual Hosts ##############################
