############################## Hosts configuration ##############################
hosts:
############################## Default host configuration ##############################  
  - id: leap

    global:
      protocol: HTTP
      host: www.leap.com
      port: 9292
      index-page: welcome.html
      error-page: error.html
      timezone: Asia/Seoul 
      locale: ko-KR
      charset: utf-8
      users:
        - username: admin
          password: '9393'
          role: ADMIN
        - username: guest
          password: '9393'
          role: GUEST
      session:
        apply: false
        length: 16
        encryption: SHA-256
        expire-days: 10      # day
        max-age-hours: 1     # hour
        timeout-seconds: 10  # second

    security:
      ip-filters: 
        allowed : [
          '*'
        ]
        forbidden : [
        ]
      context-filters: 
        allowed: [
          '*'
        ]    
        forbidden: [
        ]
      authentication: BASIC      
      encryption: 'TLS'
      keystore: './config/ssl/leap-keystore.jks'
      passphrase: '939393'

    logs: 
      path: logs/leap.log
      level: DEBUG
      details: true

    network:
      so-timeout: 5000
      backlog: 100
      keep-alive: false
      OOB-inline: false
      so-linger: true
      so-linger-timeout: 3000
      tcp-no-delay: false
      receive-buffer-size: 32368
      send-buffer-size: 128000
      request-blocking-interval-milliseconds: 10
      reponse-limit-byte-size: 10240000

    file:
      read-buffer-size: 1024000
      write-buffer-size: 1024000

    dynamic-classpath: []    


############################## Virtual host configuration ##############################
  - id: leap1

    global:
      protocol: HTTP
      host: www.leap.org
      port: 9391
      index-page: welcome.html
      error-page: error.html
      timezone: Asia/Seoul 
      locale: ko-KR
      charset: utf-8
      users:
        - username: admin
          password: '9393'
          role: ADMIN
        - username: guest
          password: '9393'
          role: GUEST
      session:
        apply: false
        length: 16
        encryption: SHA-256
        expire-days: 10      # day
        max-age-hours: 1     # hour
        timeout-seconds: 10  # second

    security:
      ip-filters: 
        allowed : [
          '*'
        ]
        forbidden : [
        ]
      context-filters: 
        allowed: [
          '*'
        ]    
        forbidden: [
        ]
      authentication: BASIC      
      encryption: 'TLS'
      keystore: './config/ssl/leap-keystore.jks'
      passphrase: '939393'

    logs: 
      path: logs/leap.log
      level: DEBUG
      details: true

    network:
      so-timeout: 5000
      backlog: 100
      keep-alive: false
      OOB-inline: false
      so-linger: true
      so-linger-timeout: 3000
      tcp-no-delay: false
      receive-buffer-size: 1024000
      send-buffer-size: 128000
      request-blocking-interval-milliseconds: 10
      reponse-limit-byte-size: 10240000

    file:
      read-buffer-size: 1024000
      write-buffer-size: 1024000

    dynamic-classpath: []    

############################## Virtual host configuration ##############################
  - id: leap2

    global:
      protocol: HTTP
      host: www.leap.org
      port: 9392
      index-page: welcome.html
      error-page: error.html
      timezone: Asia/Seoul 
      locale: ko-KR
      charset: utf-8
      users:
        - username: admin
          password: '9393'
          role: ADMIN
        - username: guest
          password: '9393'
          role: GUEST
      session:
        apply: false
        length: 16
        encryption: SHA-256
        expire-days: 10      # day
        max-age-hours: 1     # hour
        timeout-seconds: 10  # second

    security:
      ip-filters: 
        allowed : [
          '*'
        ]
        forbidden : [
        ]
      context-filters: 
        allowed: [
          '*'
        ]    
        forbidden: [
        ]
      authentication: BASIC      
      encryption: 'TLS'
      keystore: './config/ssl/leap-keystore.jks'
      passphrase: '939393'

    logs: 
      path: logs/leap.log
      level: DEBUG
      details: true

    network:
      so-timeout: 5000
      backlog: 100
      keep-alive: false
      OOB-inline: false
      so-linger: true
      so-linger-timeout: 3000
      tcp-no-delay: false
      receive-buffer-size: 1024000
      send-buffer-size: 128000
      request-blocking-interval-milliseconds: 10
      reponse-limit-byte-size: 10240000

    file:
      read-buffer-size: 1024000
      write-buffer-size: 1024000

    dynamic-classpath: []    

############################## Virtual host configuration ##############################
  - id: leap3

    global:
      protocol: HTTP
      host: www.leap.org
      port: 9393
      index-page: welcome.html
      error-page: error.html
      timezone: Asia/Seoul 
      locale: ko-KR
      charset: utf-8
      users:
        - username: admin
          password: '9393'
          role: ADMIN
        - username: guest
          password: '9393'
          role: GUEST
      session:
        apply: false
        length: 16
        encryption: SHA-256
        expire-days: 10      # day
        max-age-hours: 1     # hour
        timeout-seconds: 10  # second

    security:
      ip-filters: 
        allowed : [
          '*'
        ]
        forbidden : [
        ]
      context-filters: 
        allowed: [
          '*'
        ]    
        forbidden: [
        ]
      authentication: BASIC      
      encryption: 'TLS'
      keystore: './config/ssl/leap-keystore.jks'
      passphrase: '939393'

    logs: 
      path: logs/leap.log
      level: DEBUG
      details: true

    network:
      so-timeout: 5000
      backlog: 100
      keep-alive: false
      OOB-inline: false
      so-linger: true
      so-linger-timeout: 3000
      tcp-no-delay: false
      receive-buffer-size: 1024000
      send-buffer-size: 128000
      request-blocking-interval-milliseconds: 10
      reponse-limit-byte-size: 10240000

    file:
      read-buffer-size: 1024000
      write-buffer-size: 1024000

    dynamic-classpath: []    

############################## Virtual host configuration ##############################
  - id: leap4

    global:
      protocol: HTTP
      host: www.leap.org
      port: 9394
      index-page: welcome.html
      error-page: error.html
      timezone: Asia/Seoul 
      locale: ko-KR
      charset: utf-8
      users:
        - username: admin
          password: '9393'
          role: ADMIN
        - username: guest
          password: '9393'
          role: GUEST
      session:
        apply: false
        length: 16
        encryption: SHA-256
        expire-days: 10      # day
        max-age-hours: 1     # hour
        timeout-seconds: 10  # second

    security:
      ip-filters: 
        allowed : [
          '*'
        ]
        forbidden : [
        ]
      context-filters: 
        allowed: [
          '*'
        ]    
        forbidden: [
        ]
      authentication: BASIC      
      encryption: 'TLS'
      keystore: './config/ssl/leap-keystore.jks'
      passphrase: '939393'

    logs: 
      path: logs/leap.log
      level: DEBUG
      details: true

    network:
      so-timeout: 5000
      backlog: 100
      keep-alive: false
      OOB-inline: false
      so-linger: true
      so-linger-timeout: 3000
      tcp-no-delay: false
      receive-buffer-size: 1024000
      send-buffer-size: 128000
      request-blocking-interval-milliseconds: 10
      reponse-limit-byte-size: 10240000

    file:
      read-buffer-size: 1024000
      write-buffer-size: 1024000

    dynamic-classpath: []    
